name: mdBook Deploy

on:
  push:
    branches: [master]
    paths:
      - "spec/docs/src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: cargo install mdbook --version 0.4.36

      - name: Build mdBook
        run: mdbook build spec/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: spec/docs/book
