name: Rust CI

on:
  push:
    branches: [master]
    # paths:
    #   - "base-station/src/**"
    #   - "base-station/tests/**"
    #   - "base-station/Cargo.toml"
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "sqlite://${{ github.workspace }}/base-station/testing/test.db"
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up SQLite directory
        run: |
          mkdir -p base-station/testing && touch base-station/testing/test.db

      - name: List files
        run: ls -R

      - name: Run tests
        working-directory: base-station
        run: cargo test --all
